#pragma once
#include "CoreMinimal.h"
#include "ESBConditionType.generated.h"

UENUM()
enum ESBConditionType {
    ESBConditionType_None,
    ESBConditionType_RequireItem,
    ESBConditionType_QuestState,
    ESBConditionType_EnvState,
    ESBConditionType_PlayerLevel,
    ESBConditionType_ActorHP,
    ESBConditionType_ActorBeta,
    ESBConditionType_ActorShield,
    ESBConditionType_ActorStamina,
    ESBConditionType_ActorState,
    ESBConditionType_ActorCondition,
    ESBConditionType_ActorMovement,
    ESBConditionType_ActorEffect,
    ESBConditionType_ActorAchievement,
    ESBConditionType_ActorIsBattle,
    ESBConditionType_ItemSpawnCheck,
    ESBConditionType_ItemChargeCheck,
    ESBConditionType_NetworkEnable,
    ESBConditionType_PlayerIsDead,
    ESBConditionType_ActorInRange,
    ESBConditionType_TheaterPlaying,
    ESBConditionType_QuestTaskProgress,
    ESBConditionType_QuestTaskGroupProgress,
    ESBConditionType_AchievementProgress,
    ESBConditionType_ActorBurst,
    ESBConditionType_IsInWorld,
    ESBConditionType_IsAliveSpawnActor,
    ESBConditionType_InteractionCustomValue,
    ESBConditionType_GameOption,
    ESBConditionType_ActorFishingMode,
    ESBConditionType_IsValidActor,
    ESBConditionType_HUDNotifyCoreComplete,
    ESBConditionType_PlayGo,
    ESBConditionType_Entitlement,
    ESBConditionType_FirstTimeTrainingRoom,
    ESBConditionType_HasAggro,
    ESBConditionType_ActiveUI,
    ESBConditionType_IsHUDNotifyEmpty,
    ESBConditionType_OnlyQuestState,
    ESBConditionType_EquipLure,
    ESBConditionType_CanOpenWorldMap,
    ESBConditionType_IsTrialVersion,
    ESBConditionType_EnvStateProgress,
    ESBConditionType_IsNewGamePlus,
    ESBConditionType_PlayerLevelArray,
    ESBConditionType_IsInZone,
    ESBConditionType_ActivateDLC,
    ESBConditionType_SummerEventContents,
    ESBConditionType_ChristmasEventContents,
    ESBConditionType_ItemEquipCheck,
    ESBConditionType_PlayTime,
    ESBConditionType_HasReceivedCoupon,
    ESBConditionType_IsPhotoModeOn,
};

