#pragma once
#include "CoreMinimal.h"
#include "ESBGameUserSettingsQuality.generated.h"

UENUM()
enum ESBGameUserSettingsQuality {
    SB_GAMEUSERSETTINGS_OFF,
    SB_GAMEUSERSETTINGS_LOW,
    SB_GAMEUSERSETTINGS_MEDIUM,
    SB_GAMEUSERSETTINGS_HIGH,
    SB_GAMEUSERSETTINGS_VERYHIGH,
    SB_GAMEUSERSETTINGS_EXTENSION1,
    SB_GAMEUSERSETTINGS_EXTENSION2,
    SB_GAMEUSERSETTINGS_EXTENSION3,
};

