#pragma once
#include "CoreMinimal.h"
#include "ESBResourceDebugSubType.generated.h"

UENUM()
enum class ESBResourceDebugSubType {
    None,
    ToolData_Start,
    ToolData_EventSpawn,
    ToolData_EventItem,
    ToolData_ZoneEnvSpawn,
    ToolData_ZoneEffectVolume,
    ToolData_AreaControlVolume,
    ToolData_ZoneTrigger,
    ToolData_GuideAction,
    ToolData_LevelTargetFilter,
    ToolData_Condition,
    ToolData_ConditionGroup,
    ToolData_ZoneEvent,
    ToolData_EventObjControl,
    ToolData_EventRequestPathWay,
    ToolData_ZonePhaseEvent,
    ToolData_EventEffectVolumeControl,
    ToolData_EventEnvControl,
    ToolData_EventAreaControlVolumeControl,
    ToolData_EventActorEffect,
    ToolData_EventGuideAction,
    ToolData_EventInteractCamp,
    ToolData_EventItemAction,
    ToolData_EventQuest,
    ToolData_EventLevelSeq,
    ToolData_EventTheater,
    ToolData_EventUIAction,
    ToolData_EventZoneWarp,
    ToolData_End,
    DataTable_Start,
    DataTable_GamePlayProgressRecord,
    DataTable_EventEnvControl,
    DataTable_Achievement,
    DataTable_QuestTask,
    DataTable_End,
    InteractionGraph_Start,
    InteractionGraph_ZoneEvent,
    InteractionGraph_QuestEvent,
    InteractionGraph_End,
    Num,
    Duration,
};

