#pragma once
#include "CoreMinimal.h"
#include "ESBSkillCommandState.generated.h"

UENUM()
enum ESBSkillCommandState {
    SkillCommandState_None,
    SkillCommandState_Skill1,
    SkillCommandState_Skill2,
    SkillCommandState_Skill3,
    SkillCommandState_Skill4,
    SkillCommandState_Skill5,
    SkillCommandState_Skill6,
    SkillCommandState_Skill7,
    SkillCommandState_Skill8,
    SkillCommandState_Skill9,
    SkillCommandState_Skill10,
    SkillCommandState_Skill11,
    SkillCommandState_Skill12,
    SkillCommandState_Combination1,
    SkillCommandState_Combination2,
    SkillCommandState_CombinationCrossUp,
    SkillCommandState_CombinationCrossDown,
    SkillCommandState_CombinationCrossLeft,
    SkillCommandState_CombinationCrossRight,
    SkillCommandState_Interaction,
    SkillCommandState_NoneInputCommand,
    SkillCommandState_ToggleSprint,
    SkillCommandState_AttackLight,
    SkillCommandState_AttackStrong,
    SkillCommandState_Evade,
    SkillCommandState_Jump,
    SkillCommandState_Guard,
    SkillCommandState_SpecialCommand1,
    SkillCommandState_SpecialCommand2,
    SkillCommandState_Scan,
    SkillCommandState_BetaSkillPreCommand,
    SkillCommandState_BetaSkill1,
    SkillCommandState_BetaSkill2,
    SkillCommandState_BetaSkill3,
    SkillCommandState_BetaSkill4,
    SkillCommandState_BurstSkillPreCommand,
    SkillCommandState_BurstSkill1,
    SkillCommandState_BurstSkill2,
    SkillCommandState_BurstSkill3,
    SkillCommandState_BurstSkill4,
    SkillCommandState_TachyModeTwoKey1,
    SkillCommandState_TachyModeTwoKey2,
    SkillCommandState_FishingModeCancel,
    SkillCommandState_TPSMode,
    SkillCommandState_TPSFire,
    SkillCommandState_BetaSkillView,
    SkillCommandState_BurstSkillView,
    SkillCommandState_SwimDash,
    SkillCommandState_Num,
};

