#pragma once
#include "CoreMinimal.h"
#include "ESBShowKey.generated.h"

UENUM()
enum ESBShowKey {
    ShowKey_None = -1,
    ShowKey_Particle = 0,
    ShowKey_Animation,
    ShowKey_HitReaction,
    ShowKey_Projectile,
    ShowKey_CameraAnim,
    ShowKey_PostProcess,
    ShowKey_TimeScale,
    ShowKey_Trail,
    ShowKey_MaterialParam,
    ShowKey_CameraShake,
    ShowKey_Sound,
    ShowKey_MaterialChange,
    ShowKey_ForceFeedback,
    ShowKey_DynamicPhysicBone,
    ShowKey_Niagara,
    ShowKey_RootMotion,
    ShowKey_DynamicPhysicStop,
    ShowKey_Decal,
    ShowKey_MeshVertexShake,
    ShowKey_BoneScaleIgnore,
    ShowKey_AnimationBlendSpace,
    ShowKey_AnimationTransit,
    ShowKey_RadialForce,
    ShowKey_Ragdoll,
    ShowKey_ChangeAttachTo,
    ShowKey_AnimationByMeshSlot,
    ShowKey_DepthOfField,
    ShowKey_PlayShow,
    ShowKey_AnimNodeGroundCollision,
    ShowKey_AnimNodeTargetTracking,
    ShowKey_CreateDestructible,
    ShowKey_RuleMove,
    ShowKey_MovementBone,
    ShowKey_PostProcessMaterial,
    ShowKey_MaterialCollectionParam,
    ShowKey_DeactiveParticle,
    ShowKey_SoundVolumeAdjuster,
    ShowKey_Actor,
    ShowKey_LockOnTarget,
    ShowKey_Effect,
    ShowKey_SkillResult,
    ShowKey_ControlCamLagSpeed,
    ShowKey_Cable,
    ShowKey_LockOnTargetBone,
    ShowKey_Vibration,
    ShowKey_CreateStaticMesh,
    ShowKey_PlayTheater,
    ShowKey_Visibility,
    ShowKey_ClientEvent,
    ShowKey_AnimBPSetValue,
    ShowKey_PoseSnapshot,
    ShowKey_NotifyEvent,
    ShowKey_Delete1,
    ShowKey_SetAIDecorator,
    ShowKey_Delete2,
    ShowKey_AttachSocketToSocket,
    ShowKey_CharacterSE,
    ShowKey_Fly,
    ShowKey_ActorAnim,
    ShowKey_ActorEventNotification,
    ShowKey_UIStudioSequence,
    ShowKey_ActorCompVisible,
    ShowKey_WindVolume,
    ShowKey_ControlLockOnBlend,
    ShowKey_SoundEvent,
    ShowKey_AnimBPSetValue_String,
    ShowKey_CameraEyeTracking,
    ShowKey_ControlCameraVolume,
    ShowKey_Num,
};

