#pragma once
#include "CoreMinimal.h"
#include "ESBCharacterCustomAnim.generated.h"

UENUM()
enum ESBCharacterCustomAnim {
    ESBCharacterCustomAnim_None = -1,
    ESBCharacterCustomAnim_Custom1 = 0,
    ESBCharacterCustomAnim_Custom2,
    ESBCharacterCustomAnim_Custom3,
    ESBCharacterCustomAnim_Custom4,
    ESBCharacterCustomAnim_Custom5,
    ESBCharacterCustomAnim_Custom6,
    ESBCharacterCustomAnim_Custom7,
    ESBCharacterCustomAnim_Custom8,
    ESBCharacterCustomAnim_Custom9,
    ESBCharacterCustomAnim_Custom10,
    ESBCharacterCustomAnim_Custom11,
    ESBCharacterCustomAnim_Custom12,
    ESBCharacterCustomAnim_Custom13,
    ESBCharacterCustomAnim_Custom14,
    ESBCharacterCustomAnim_Custom15,
    ESBCharacterCustomAnim_Custom16,
    ESBCharacterCustomAnim_Custom17,
    ESBCharacterCustomAnim_Custom18,
    ESBCharacterCustomAnim_Custom19,
    ESBCharacterCustomAnim_Custom20,
    ESBCharacterCustomAnim_HitStandLight1Left,
    ESBCharacterCustomAnim_HitStandLight1Right,
    ESBCharacterCustomAnim_HitStandLight1Back,
    ESBCharacterCustomAnim_HitStandLight1Front,
    ESBCharacterCustomAnim_HitStandLight2Left,
    ESBCharacterCustomAnim_HitStandLight2Right,
    ESBCharacterCustomAnim_HitStandLight2Back,
    ESBCharacterCustomAnim_HitStandLight2Front,
    ESBCharacterCustomAnim_HitStandStrong1Left,
    ESBCharacterCustomAnim_HitStandStrong1Right,
    ESBCharacterCustomAnim_HitStandStrong1Back,
    ESBCharacterCustomAnim_HitStandStrong1Front,
    ESBCharacterCustomAnim_HitStandStrong2Left,
    ESBCharacterCustomAnim_HitStandStrong2Right,
    ESBCharacterCustomAnim_HitStandStrong2Back,
    ESBCharacterCustomAnim_HitStandStrong2Front,
    ESBCharacterCustomAnim_Groggy_Start,
    ESBCharacterCustomAnim_Groggy_Loop,
    ESBCharacterCustomAnim_Groggy_End,
    ESBCharacterCustomAnim_Airborne_Loop,
    ESBCharacterCustomAnim_KnockDown_Start_Front,
    ESBCharacterCustomAnim_KnockDown_Start_Back,
    ESBCharacterCustomAnim_KnockDown_Loop,
    ESBCharacterCustomAnim_KnockDown_End,
    ESBCharacterCustomAnim_Caution_LeftToIdle,
    ESBCharacterCustomAnim_Caution_RightToIdle,
    ESBCharacterCustomAnim_HitSwordNormalLinkAttack1,
    ESBCharacterCustom_HitSwordNormalFinishLinkAttack1,
    ESBCharacterCustom_HitSwordAirDropAttack1,
    ESBCharacterCustom_HitSwordNormalBackStab1,
    ESBCharacterCustomAnim_Num,
};

