#include "SBStreamingLevelLoadingBarrierVolumeVisualizerComponent.h"

USBStreamingLevelLoadingBarrierVolumeVisualizerComponent::USBStreamingLevelLoadingBarrierVolumeVisualizerComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


